### ISSUE TITLE
west init duplicates settings from ~/.westconfig

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/west#213] opened 2019-02-22 09:49 UTC
Running `west init` will create the config file `.west/config` and populate this file with
```
[manifest]
path = <manifest-path>
```

However, if the file, `~/.westconfig` exists, then all settings from that file will also be copied into `.west/config` which basically means, that if user later changes the settings in `~/.westconfig` those settings will not be picked used, as they also exists inside `<project>/.west/config`

**Comment by mbolivar** [comment] 2019-05-15 19:27
@tejlmand I can't reproduce this on master:

```
$ cat ~/.westconfig
[zephyr]
base-prefer = configfile
[foo]
bar = baz

$ west init >/dev/null 2>&1
$ cat .west/config
[manifest]
path = zephyr
[zephyr]
base = zephyr
$ cat ~/.westconfig
[zephyr]
base-prefer = configfile
[foo]
bar = baz
```

Still valid for you?

**Comment by mbolivar** [comment] 2019-05-25 07:06
Closing since I can't reproduce.

**Closed by mbolivar** 2019-05-25 07:06 UTC
Labels: bug
